spring:
  datasource:
    url: jdbc:mysql://192.168.200.103:13310/easy_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: hkzs
    password: dev123456
  data:
    redis:
      host: 192.168.200.103
      port: 16379
      password: 123456
      database: 14
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.103:8848
        namespace: 25afecbf-2284-4a55-a792-3f54d1d9c4ec
        username: nacos
        password: nacos