server:
  port: 30431
spring:
  application:
    name: easy-service-file
  config:
    import:
      - optional:application-datasource.yml
      - optional:application-web.yml
      - optional:application-token.yml
      - optional:application-dubbo.yml
  profiles:
    active: prod

mybatis-plus:
  mapper-package: com.easy.**.dao

logging:
  level:
    root: info

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.easy.file
# knife4j的增强配置，不需要增强可以不配
knife4j:
  documents:
    - group: default
      name: 文件服务

dubbo:
  application:
    qos-port: 23335
  scan:
    # 接口实现类扫描
    base-packages: com.easy.**.service